### PR TITLE
Rostov-on-Don airport changed Iata code from ROV to RVI on 2017-11-27

### PR DESCRIPTION
**Pull request by mtrampont**
Hi,

According to [Rostov-on-Don](https://en.wikipedia.org/wiki/Rostov-on-Don_Airport) and the new [Platov airport](Platov_International_Airport) wikipedia pages, although the transfert of operations from Rostov-on-Don to Platov was completed on the 2017-12-07, the new Platov airport was opened on the 2017-11-27 and the IATA code of Rostov-on-Don was changed from ROV to RVI at that time.

This PR is updating the validity dates of the corresponding 3 entries to reflect that.

Best regards,

Mathieu Trampont

### CODE REVIEW

**Comment by mtrampont** [comment]
Hi,

I understand that optd_por_public.csv is generated and I should not update it that way. However, it is unclear to me what is the proper way to update for such corrections of validity dates.
Any Help ?

Best regards,

Mathieu Trampont

**Comment by denisarnaud** [comment]
Thanks Mathieu!

As a matter of fact, I already integrated that change of airport within 2bbaab3. And I intentionally used the 7 December 2017 as change date, as it corresponds to the operational transfer date. It means that any record specifying ``ROV`` with a date of departure before the 7 December 2017 (for instance, within a schedule or within a booking record), including for dates of departure after the 27 November 2017, was referring to [Rostov-on-Don](http://en.wikipedia.org/wiki/Rostov-on-Don_Airport), as the new [Platov airport](http://github.com/opentraveldata/opentraveldata/pull/Platov_International_Airport) was not yet operational.
For that reason, it is better to use the operational date of transfer rather than the official date of assignment change.

**Comment by denisarnaud** [comment]
> I understand that optd_por_public.csv is generated and I should not update it that way. However, it is unclear to me what is the proper way to update for such corrections of validity dates.

You can for instance see the pull request #80 .

**Comment by mtrampont** [comment]
Hi Denis,

Problem is we have records using the RVI code between 2017-11-27 and 2017-12-07 instead of ROV. But opentraveldata won't match any PoR for these. So at least could we use 2017-11-27 for the date from of the RVI airport ?

Best regards,

Mathieu Trampont

**Comment by denisarnaud** [comment]
> Problem is we have records using the RVI code between 2017-11-27 and 2017-12-07 instead of ROV. But opentraveldata won't match any PoR for these. So at least could we use 2017-11-27 for the date from of the RVI airport ?

Yes, absolutely, thanks!

**Pull request closed without merging**
