### PR TITLE
Update airline code for 8R iata code

### PR DESCRIPTION
**Pull request by cfuentesgrobas**

### CODE REVIEW

**Comment by alexprengere** [comment]
Thank you for the PR, can you rebase on top of current master and force push your results to your branch? There are conflicts that prevent online merging right now.

**Comment by alexprengere** [comment]
Yes, I can merge without rebasing, but this is not the policy we use. I can do it myself if you want, just not from the GitHub UI.

**Comment by cfuentesgrobas** [comment]
I made a rebase + force push but I do not see any changes in the PR. Can you please check?

**Comment by alexprengere** [comment]
I did a squash & merge, which results in the same history 😉

**Pull request merged**
