### PR TITLE
add the fictitious point QTV

### PR DESCRIPTION
**Pull request by AsmaaFillatre**

### CODE REVIEW

**Comment by denisarnaud** [comment]
Thanks Asmaa!

Please note that the [optd_por_public.csv file](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_public.csv) is generated. The one you should update, instead, is [optd_por_best_known_so_far.csv](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_best_known_so_far.csv).

Could you please ``rebase`` your ``master`` branch on the latest changes, and alter the [optd_por_best_known_so_far.csv file](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_best_known_so_far.csv)?

**Comment by AsmaaFillatre** [comment]
Thanks for your replay Denis,
It is strange because the point QTV is already in optd_por_best_known_so_far.csv. So why it is not going to optd_por_public.csv after the generation of this later ?

**Comment by denisarnaud** [comment]
Because it's not associated with any Geonames ID/POR yet

**Comment by denisarnaud** [comment]
Basically, we just need the accurate geo-coordinates and the name. Then I'll create the Geonames record

**Comment by AsmaaFillatre** [comment]
QTV is a fictitious point but from optd_por_ref.csv, we have those geo-coordinates  QTV,46,6.167. I guess it has no name associated.

**Comment by denisarnaud** [comment]
Fixed by a65eba17

**Comment by henrik242** [comment]
> Please note that the optd_por_public.csv file is generated. 

It would be nice if that file was inside a `generated` folder or something... :)

**Comment by denisarnaud** [comment]
>  It would be nice if that file was inside a generated folder or something... :)

You are absolutely right. However, it has been the place where people are used to find that file for a while now. If we move the generated files out of that directory, quite a few automated processes (retrieving that file) will fail...

**Pull request closed without merging**
