### PR TITLE
Add a lot of time zones

### PR DESCRIPTION
**Pull request by henrik242**
Add a lot of missing time zones.

Source: https://github.com/hroptatyr/dateutils/blob/tzmaps/iata.tzmap

### CODE REVIEW

**Comment by henrik242** [comment]
`/add_reviewer  @denisarnaud`

:)

**Comment by denisarnaud** [comment]
> /add_reviewer @denisarnaud
> :)

Indeed, thanks for your new contribution... and sorry to (potentially) disappoint you again here: the [opentraveldata/optd_por_tz.csv data file](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_tz.csv) is only used for POR (points of reference), for which there is no counterpart on Geonames (for instance, the Geonames ID is set to 0 in the [opentraveldata/optd_por_best_known_so_far.csv file](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_best_known_so_far.csv)) yet. Because when a POR is known to Geonames, the time-zone details are derived from that latter, and given in the [opentraveldata/optd_por_public.csv file](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_public.csv). For instance:
```csv
AAA^...^Pacific/Tahiti^-10.0^-10.0^-10.0^...
BOM^...^Asia/Kolkata^5.5^5.5^5.5^...
CHI^...^America/Chicago^-6.0^-5.0^-6.0^...
SVO^...^Europe/Moscow^3.0^3.0^3.0^...
```

That being said, we would be interested by your contribution taking another shape:
* Check whether the time-zone details are correct in the [opentraveldata/optd_por_public.csv file](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_public.csv)
* And, if not, please [open an issue](https://github.com/opentraveldata/opentraveldata/issues/new)

If you go that way (of contributing), your help would be welcome on the [Service Delivery Quality / Quality Assurance (QA) project](https://github.com/service-delivery-quality/quality-assurance), and more specifically in contributing to:
* [Python data quality checking scripts](https://github.com/service-delivery-quality/quality-assurance/tree/master/samples/opentraveldata)
* Or in analyzing the output of those scripts (which, by definition, should produce only data issue records) and fixing the corresponding [OpenTravelData](https://github.com/opentraveldata/opentraveldata) master files.

**Comment by denisarnaud** [comment]
> Hm. You wrote somewhere else that opentraveldata/optd_por_public.csv is generated. Where is the timezone source data?

Yes, the [opentraveldata/optd_por_public.csv file](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_public.csv) is generated. Nevertheless, as [explained above](https://github.com/opentraveldata/opentraveldata/pull/85#issuecomment-380125225), Geonames provides all the details about the time-zones.

For instance, if you click on the ["pencil" (update) button](https://fontawesome.com/icons/pencil-alt?style=solid) on a Geonames POR (eg, http://www.geonames.org/8299088), you will see the``timezon`` field associated to that POR. Then, Geonames has internal tables to derive the corresponding time off-sets, ie, GMT, DST and raw offsets.

So, if you find some errors in time-zone details, either:
* The POR is known to Geonames, and you can alter the time-zone details directly on the Geonames record (eg, http://www.geonames.org/8299088), in the ``timezone`` field. Alternatively, you can post a message on the [Geonames mailing list](https://groups.google.com/forum/#!forum/geonames).
* The POR is unknown from Geonames. The time-zone information should be provided in the [opentraveldata/optd_por_tz.csv file](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_tz.csv).

**Comment by henrik242** [comment]
Thanks for the explanation! I didn't realize that "Geonames" was a third party service.

**Pull request closed without merging**
